#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# This script is a stub for invoking "@@ARG0@@" with the version of Node
# with which Marlin was built.  If you're looking at this inside the Marlin
# repo, you're looking at a template that's used to build per-command stubs.
#
marlin_root="$(dirname $(readlink -f "$BASH_SOURCE[0]"))/.."
node="$marlin_root/build/node/bin/node"
cmd="$marlin_root/node_modules/@@CMDBASE@@/@@ARG0@@"
exec "$node" "$cmd" "$@"
