#!/usr/bin/env node

/*
 * mrjob: submit jobs directly to Marlin via Moray (i.e. not through Muskie)
 * This is a dev tool.
 */

var mod_assert = require('assert');
var mod_path = require('path');
var mod_url = require('url');

var mod_bunyan = require('bunyan');
var mod_extsprintf = require('extsprintf');
var mod_getopt = require('posix-getopt');
var mod_jsprim = require('jsprim');
var mod_uuid = require('node-uuid');
var mod_vasync = require('vasync');
var mod_wordwrap = require('wordwrap');
var wrap = mod_wordwrap(80);

var mod_mautil = require('../lib/util');
var mod_moray = require('moray');
var mod_worker = require('../lib/worker/worker');

var msArg0 = mod_path.basename(process.argv[1]);
var msUsage = [
    'USAGE: mrjob submit   [-i id] [-n name] [-m exec] [-r exec] ...',
    '       mrjob addkeys  jobid [key ...]',
    '       mrjob endinput jobid',
    '       mrjob cancel   jobid',
    '',
    '    Submits a new job to Marlin via Moray, or modifies a previously ',
    '    submitted job.',
    '',
    'SUBCOMMANDS',
    '',
    '   submit          Submit a new job without ending input.',
    '',
    '      -i id          Use "id" for the job\'s id',
    '      -m exec        Append a map phase with body "exec"',
    '      -n name        Use "name" for the job\'s name',
    '      -r exec        Append a reduce phase with body "exec"',
    '',
    '      With no -m or -r options, the job gets one map phase.',
    '',
    '   addkeys         Submit new keys for a job.',
    '',
    '   endinput        Indicate that no further keys will be added for a job.',
    '',
    '   cancel          Mark a job job cancelled.',
    '',
    'EXAMPLE: Create a "word count" job',
    '',
    '    # mrjob submit -m wc -r "awk {sum += $1} END { print sum; }"',
    '    34cae1fd-8f9e-48cb-9163-7e2b365fc394',
    '',
    '    # mrjob addkeys 34cae1fd-8f9e-48cb-9163-7e2b365fc394 key1 ...',
    '    # mrjob endinput 34cae1fd-8f9e-48cb-9163-7e2b365fc394'
].join('\n');

var msPhases = [];
var msJobName = 'mrsubmit job';
var msJobId = mod_uuid.v4();
var msMorayUrl = process.env['MORAY_URL'];

var msBuckets;	/* bucket names */
var msClient;	/* Moray client */
var msLog;	/* bunyan logger */
var msUrlConf;	/* Moray URL configuration */
var msCommands = {
    'submit': cmdSubmit,
    'addkeys': cmdAddkeys,
    'endinput': cmdEndinput,
    'cancel': cmdCancel
};

function usage()
{
	console.error(msUsage);
	process.exit(2);
}

function main()
{
	var subcmd, conf;

	if (process.argv.length < 3)
		usage();

	subcmd = process.argv[2];

	if (!msCommands.hasOwnProperty(subcmd))
		usage();

	if (!msMorayUrl) {
		console.error('MORAY_URL must be specified in the environment');
		process.exit(2);
	}

	/* XXX commonize with mrstat */
	msLog = new mod_bunyan({
	    'name': msArg0,
	    'level': process.env['LOG_LEVEL'] || 'info',
	    'stream': process.stderr
	});

	conf = mod_mautil.readConf(msLog, mod_worker.mwConfSchema,
	    mod_path.join(__dirname, '../etc/config.coal.json'));
	msBuckets = conf['buckets'];
	mod_assert.ok(msBuckets['job']);
	mod_assert.ok(msBuckets['jobinput']);
	mod_assert.ok(msBuckets['task']);
	mod_assert.ok(msBuckets['taskinput']);
	mod_assert.ok(msBuckets['taskoutput']);

	msUrlConf = mod_url.parse(msMorayUrl);

	msCommands[subcmd]();
}

function clientInit(callback)
{
	msClient = mod_moray.createClient({
	    'host': msUrlConf['hostname'],
	    'port': parseInt(msUrlConf['port'], 10),
	    'log': msLog
	});

	msClient.on('connect', callback);
}

function clientFini()
{
	msClient.close();
}

function cmdSubmit()
{
	var parser, option;

	parser = new mod_getopt.BasicParser('c:m:n:r:',
	    process.argv.slice(1));

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'i':
			msJobId = option.optarg;
			break;

		case 'n':
			msJobName = option.optarg;
			break;

		case 'm':
		case 'r':
			msPhases.push({
			    'type': option.option == 'm' ?
				'storage-map' : 'reduce',
			    'exec': option.optarg
			});
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	if (msPhases.length === 0)
		msPhases.push({ 'type': 'storage-map', 'exec': 'echo' });

	var now = mod_jsprim.iso8601(Date.now());
	var job = {
	    'jobId': msJobId,
	    'jobName': msJobName,
	    'owner': process.env['USER'] || 'nobody',
	    'phases': msPhases,
	    'state': 'queued',
	    'timeCreated': now
	};

	clientInit(function () {
		msClient.putObject(msBuckets['job'], msJobId, job,
		    function (err) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			console.log(msJobId);
			clientFini();
		    });
	});
}

function cmdAddkeys()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];
	var keys = process.argv.slice(4);

	if (keys.length === 0)
		return;

	clientInit(function () {
		mod_vasync.forEachParallel({
		    'func': function (key, callback) {
			var keyid = mod_uuid.v4();
			msClient.putObject(msBuckets['jobinput'], keyid,
			    { 'jobId': jobid, 'key': key }, function (err) {
				if (!err)
					console.log(key);
				else
					console.error('%s: key "%s": %s',
					    msArg0, key, err.message);
				callback();
			    });
		    },
		    'inputs': keys
		}, clientFini);
	});
}

function cmdEndinput()
{
	if (process.argv.length < 4)
		usage();

	jobReadModifyWrite(process.argv[3], function (job) {
		if (job['timeInputDone'])
			console.error('warning: job\'s input already ended');

		if (job['timeCancelled'])
			console.error('warning: job already cancelled');

		if (job['state'] == 'done')
			console.error('warning: job already done');

		job['timeInputDone'] = mod_jsprim.iso8601(Date.now());
	});
}

function cmdCancel()
{
	if (process.argv.length < 4)
		usage();

	jobReadModifyWrite(process.argv[3], function (job) {
		if (job['timeCancelled'])
			console.error('warning: job already cancelled');

		if (job['state'] == 'done')
			console.error('warning: job already done');

		job['timeCancelled'] = mod_jsprim.iso8601(Date.now());
	});
}

function jobReadModifyWrite(jobid, modifycb)
{
	var record;

	mod_vasync.pipeline({
	    'funcs': [
		function (_, callback) {
			clientInit(callback);
		},
		function (_, callback) {
			msClient.getObject(msBuckets['job'], jobid,
			    { 'noCache': true }, function (err, rec) {
				record = rec;
				callback(err, rec);
			    });
		},
		function (_, callback) {
			modifycb(record['value']);
			msClient.putObject(msBuckets['job'], jobid,
			    record['value'], { 'etag': record['_etag'] },
			    callback);
		},
		clientFini
	    ]
	}, function (err) {
		if (err) {
			console.error('%s: %s', msArg0, err.message);
			process.exit(1);
		}
	});
}

main();
