#!/usr/bin/env node

/*
 * mrjob: submit jobs directly to Marlin via Moray (i.e. not through Muskie)
 * This is a dev tool.
 */

var mod_assert = require('assert');
var mod_path = require('path');
var mod_url = require('url');

var mod_bunyan = require('bunyan');
var mod_extsprintf = require('extsprintf');
var mod_getopt = require('posix-getopt');
var mod_jsprim = require('jsprim');
var mod_tab = require('tab');
var mod_uuid = require('node-uuid');
var mod_verror = require('verror');
var mod_vasync = require('vasync');
var mod_wordwrap = require('wordwrap');

var sprintf = mod_extsprintf.sprintf;
var wrap = mod_wordwrap(80);
var wrap4 = mod_wordwrap(4, 80);
var println = function () {
	console.log(mod_extsprintf.sprintf.apply(null,
	    Array.prototype.slice.call(arguments)));
};

var mod_marlin = require('../lib/marlin');

var msArg0 = mod_path.basename(process.argv[1]);
var msUsage = [
    'USAGE: mrjob subcmd [options] [arguments]',
    '       mrjob [-h | -? | --help]',
    '',
    '       mrjob list     [-H] [-o field1[,field2...]] [-c] [-s state]',
    '                      [-t sec] [-u user] [-w worker]',
    '       mrjob submit   [-a key] [-c count] [-i id] [-n name] [-d size]',
    '                      [-p jobid] [-t authToken] [-m exec] [-r exec] ...',
    '       mrjob addkeys  jobid [key ...]',
    '       mrjob cancel   jobid',
    '       mrjob endinput jobid',
    '',
    '       mrjob errors   jobid',
    '       mrjob failed   jobid',
    '       mrjob get      [-v] jobid',
    '       mrjob inputs   jobid',
    '       mrjob log      jobid',
    '       mrjob outputs  jobid'
].join('\n');

var msHelp = [
    '',
    '    Manages Marlin jobs via Moray.',
    '',
    'SUBCOMMANDS',
    '',
    '   submit [-a key] [-c count] [-i id] [-n name] [-t token]',
    '          [-m exec] [-r exec]',
    '',
    '      Submit a new job without ending input.',
    '',
    '          -a key         Append the named asset to the following task',
    '          -c count       Use "count" concurrent reducers for the next ' +
	'task',
    '          -d size        Maximum DRAM for each task (megabytes)',
    '          -i id          Use "id" for the job\'s id',
    '          -m exec        Append a map phase with body "exec"',
    '          -n name        Use "name" for the job\'s name',
    '          -p jobid       Indicate that output should be streamed from ',
    '                         the output of job "jobid"',
    '          -r exec        Append a reduce phase with body "exec"',
    '          -t token       Auth token',
    '',
    '      With no -m or -r options, the job gets one map phase.',
    '',
    '   addkeys jobid [key ...]',
    '',
    '       Submit new keys for a job (which may or may not already exist).',
    '',
    '   inputs jobid',
    '',
    '       Lists all keys submitted for a job.',
    '',
    '   endinput jobid',
    '',
    '       Indicate that no further keys will be added for a job.',
    '',
    '   cancel jobid',
    '',
    '       Mark a job job cancelled.',
    '',
    '   outputs jobid',
    '',
    '       List objects emitted by a job.',
    '',
    '   failed jobid',
    '',
    '       Lists job input keys whose processing failed, either during the ',
    '       first phase or a subsequent phase.  Note that failures during or ',
    '       after any reduce phase cannot be tracked back to the original ',
    '       input key, so such failures will not be represented in this ',
    '       output.',
    '',
    '   errors jobid',
    '',
    '       Lists errors that occurred while processing the given job.',
    '',
    '   list [-H] [-o field1[,field2...]] [-c] [-s state] [-t sec] [-u user]',
    '        [-w worker]',
    '',
    '       Lists all jobs.  The default output mode is a human-readable, ',
    '       unstable output format.  With -H, the output is a simple table ',
    '       with no header row.  Individual columns may be selected using -o',
    '       as with ps(1) and other tools.  -o implies -H.',
    '',
    '       Other options control filtering:',
    '',
    '           -c              only cancelled jobs',
    '           -s state        only jobs in state "state"',
    '           -t sec          only jobs completed in last "sec" seconds',
    '           -u user         only jobs owned by "user"',
    '           -w worker       only jobs currently run by worker "worker"',
    '',
    '   get [-v] jobid',
    '',
    '       Fetch details about the given job.',
    '',
    '   log jobid',
    '',
    '       Fetch history about the given job.',
    '',
    'MORAY',
    '',
    '   The remote Moray instance to use must be specified via the MORAY_URL ',
    '   environment variable, which should have the form "tcp://host:port/"',
    '',
    'EXAMPLE: Create a "word count" job',
    '',
    '    # mrjob submit -m wc -r "awk {sum += $1} END { print sum; }"',
    '    34cae1fd-8f9e-48cb-9163-7e2b365fc394',
    '',
    '    # mrjob addkeys 34cae1fd-8f9e-48cb-9163-7e2b365fc394 key1 ...',
    '    # mrjob endinput 34cae1fd-8f9e-48cb-9163-7e2b365fc394',
    '',
    'COLUMNS',
    '',
    '    The following columns are available when listing jobs:'
].join('\n');

var msPhases = [];
var msAssets = [];			/* assets (for next phase) */
var msCount = 1;			/* reducer count (for next phase) */
var msDram;				/* DRAM cap (for next phase) */
var msPipeSource;			/* source of job's input */
var msJobName = 'mrsubmit job';
var msJobId = mod_uuid.v4();
var msAuthToken;
var msMorayUrl = process.env['MORAY_URL'];
var msParseable = false;		/* whether output should be parseable */
var msVerbose = 0;			/* whether output should be verbose */
var msColumns;				/* user-specified list of columns */

var msApi;	/* marlin api */
var msLog;	/* bunyan logger */
var msCommands = {
    'submit': cmdSubmit,
    'addkeys': cmdAddkeys,
    'inputs': cmdInputs,
    'endinput': cmdEndinput,
    'cancel': cmdCancel,
    'list': cmdList,
    'outputs': cmdOutputs,
    'errors': cmdErrors,
    'failed': cmdFailed,
    'get': cmdGet,
    'log': cmdLog
};

/* default set of columns for list-of-jobs */
var msColsJobs = [ 'JobId', 'S', 'NPh', 'Modified' ];

/* node-tab configuration for list-of-jobs table */
var msFieldsJobs = {
    'assigned': {
	'label': 'ASSIGNED',
	'width': 24
    },
    'cancelled': {
	'label': 'CANCELLED',
	'width': 24
    },
    'created': {
	'label': 'CREATED',
	'width': 24
    },
    'done': {
	'label': 'DONE',
	'width': 24
    },
    'inputdone': {
	'label': 'INPUTDONE',
	'width': 24
    },
    'jobid': {
	'label': 'JOBID',
	'width': 36
    },
    'jobname': {
	'label': 'JOBNAME',
	'width': 24
    },
    'modified': {
	'label': 'MODIFIED',
	'width': 24,
	'doc': 'last modified time'
    },
    'nin': {
	/* XXX remove? */
	'label': 'NIN',
	'width': 5,
	'align': 'right'
    },
    'nph': {
	'label': 'NPH',
	'width': 3,
	'align': 'right',
	'doc': 'number of phases'
    },
    'owner': {
	'label': 'OWNER',
	'width': 36
    },
    's': {
	'label': 'S',
	'width': 5,
	'align': 'right',
	'doc': 'state'
    },
    'worker': {
	'label': 'WORKER',
	'width': 36
    }
};

/*
 * Aliases: the keys in this object may be used as field names with -o, but
 * each one is just an alias for the corresponding value.
 */
var msFieldAliases = {
    'crtime': 'created',
    'cust': 'owner',
    'customer': 'owner',
    'mtime': 'modified',
    'state': 's',
    'user': 'owner'
};

/* Mapping of task state values to a shorter form for display. */
var msTaskStates = {
    'aborted': 'abrt',
    'dispatched': 'disp',
    'running': 'run',
    'cancelled': 'cncl',
    'done': 'done'
};

function usage()
{
	console.error(msUsage);
	process.exit(2);
}

function help()
{
	function docFields(conf, list) {
		return (Object.keys(conf).map(function (f) {
			var rv = conf[f]['label'];
			if (conf[f]['doc'])
				rv += ' (' + conf[f]['doc'] + ')';
			return (rv);
		}).join(', '));
	}

	console.error(msUsage);
	console.error(msHelp);
	console.error(wrap4(docFields(msFieldsJobs) + '\n'));
	process.exit(2);
}

function main()
{
	var subcmd;

	if (process.argv.length < 3)
		usage();

	subcmd = process.argv[2];

	if (subcmd == '-h' || subcmd == '-?' || subcmd == '--help')
		help();

	if (!msCommands.hasOwnProperty(subcmd))
		usage();

	if (!msMorayUrl) {
		console.error('MORAY_URL must be specified in the environment');
		process.exit(2);
	}

	msLog = new mod_bunyan({
	    'name': msArg0,
	    'level': process.env['LOG_LEVEL'] || 'warn',
	    'stream': process.stderr
	});

	msCommands[subcmd]();
}

function clientInit(callback)
{
	mod_marlin.createClient({
	    'moray': { 'url': msMorayUrl },
	    'log': msLog
	}, function (err, api) {
		if (err) {
			console.error('%s: %s', msArg0, err.message);
			process.exit(1);
		}

		msApi = api;
		callback(msApi);
	});
}

function clientFini()
{
	msApi.close();
}

function cmdSubmit()
{
	var parser, option;

	parser = new mod_getopt.BasicParser('a:c:d:i:m:n:p:r:t:',
	    process.argv.slice(1));

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'a':
			msAssets.push(option.optarg);
			break;

		case 'c':
			msCount = parseInt(option.optarg, 10);
			if (isNaN(msCount) || msCount < 1 || msCount >= 1024) {
				console.error('%s: invalid count', msArg0);
				usage();
			}
			break;

		case 'd':
			msDram = parseInt(option.optarg, 10);
			if (isNaN(msDram) || msDram < 128) {
				console.error('%s: invalid size', msArg0);
				usage();
			}
			break;

		case 'i':
			msJobId = option.optarg;
			break;

		case 'n':
			msJobName = option.optarg;
			break;

		case 'p':
			msPipeSource = option.optarg;
			break;

		case 't':
			msAuthToken = option.optarg;
			break;

		case 'm':
		case 'r':
			var phase = {
			    'type': option.option == 'm' ?
				'storage-map' : 'reduce',
			    'exec': option.optarg
			};

			if (msAssets.length > 0) {
				phase['assets'] = msAssets;
				msAssets = [];
			}

			if (msCount > 1) {
				if (option.option != 'r') {
					console.error('%s: -c invalid for ' +
					    'map phases', msArg0);
					usage();
				}

				phase['count'] = msCount;
				msCount = 1;
			}

			if (msDram !== undefined) {
				if (option.option != 'r') {
					console.error('%s: -d invalid for ' +
					    'map phases', msArg0);
					usage();
				}

				phase['memory'] = msDram;
				msDram = undefined;
			}

			msPhases.push(phase);
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	if (msPhases.length === 0)
		msPhases.push({ 'type': 'storage-map', 'exec': 'echo' });

	if (!msAuthToken) {
		console.error('%s: auth token (-t) is required', msArg0);
		process.exit(1);
	}

	var job = {
	    'jobId': msJobId,
	    'jobName': msJobName,
	    'phases': msPhases,
	    'owner': process.env['USER'],
	    'authToken': msAuthToken
	};

	if (msPipeSource)
		job['input'] = msPipeSource;

	clientInit(function (api) {
		api.jobCreate(job, function (err, jobid) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			console.log(jobid);
			clientFini();
		});
	});
}

function cmdAddkeys()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];
	var keys = process.argv.slice(4);

	if (keys.length === 0)
		return;

	clientInit(function (api) {
		mod_vasync.forEachParallel({
		    'inputs': keys,
		    'func': function (key, callback) {
			api.jobAddKey(jobid, key, function (err) {
				if (!err)
					console.log(key);
				else
					console.error('%s: key "%s": %s',
					    msArg0, key, err.message);
				callback();
			});
		    }
		}, clientFini);
	});
}

function cmdInputs()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchInputs(jobid);

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to list inputs: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('key', function (key) {
			console.log(key);
		});

		rv.on('end', clientFini);
	});
}

function cmdEndinput()
{
	if (process.argv.length < 4)
		usage();

	var opts = {
	    'retry': {
		'retries': 1,
		'maxTimeout': 1000
	    }
	};

	clientInit(function (api) {
		api.jobEndInput(process.argv[3], opts, function (err, record) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			var job = record['value'];
			if (job['timeInputDone'])
				console.error(
				    'warning: job\'s input already ended');

			if (job['timeCancelled'])
				console.error('warning: job already cancelled');

			if (job['state'] == 'done')
				console.error('warning: job already done');

			clientFini();
		});
	});
}

function cmdCancel()
{
	if (process.argv.length < 4)
		usage();

	var opts = {
	    'retry': {
		'retries': 1,
		'maxTimeout': 1000
	    }
	};

	clientInit(function (api) {
		api.jobCancel(process.argv[3], opts, function (err, record) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			var job = record['value'];
			if (job['timeCancelled'])
				console.error('warning: job already cancelled');

			if (job['state'] == 'done')
				console.error('warning: job already done');

			clientFini();
		});
	});
}

function cmdOutputs()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		api.jobFetch(jobid, function (err, record) {
			if (err) {
				console.error('%s: job "%s": ' +
				    'failed to fetch: %s', msArg0, jobid,
				    err.message);
				process.exit(1);
			}

			var rv = api.jobFetchOutputs(jobid,
			    record['value']['phases'].length - 1,
			    { 'limit': 1000 });

			rv.on('error', function (suberr) {
				console.error('%s: job "%s": failed to list ' +
				    'outputs: %s', msArg0, jobid,
				    suberr.message);
				process.exit(1);
			});

			rv.on('key', function (key) {
				console.log('%s', key);
			});

			rv.on('end', clientFini);
		});
	});
}

function cmdErrors()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchErrors(jobid);

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to list errors: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('err', function (error) {
			console.log('%s: %s', error['what'], error['message']);
			if (error['stderr'])
			    console.log('    (see %s)', error['stderr']);
		});

		rv.on('end', clientFini);
	});
}

function cmdFailed()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchFailedJobInputs(jobid);

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to list failed: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('key', function (key) {
			console.log(key);
		});

		rv.on('end', clientFini);
	});
}

function cmdList()
{
	var argv, parser, option, options;

	argv = process.argv.slice(1);
	parser = new mod_getopt.BasicParser('Ho:cs:t:u:w:', argv);
	options = {};

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'c':
			options['cancelled'] = true;
			break;

		case 's':
			options['state'] = option.optarg;
			break;

		case 't':
			options['doneSince'] = parseInt(option.optarg, 10);
			if (isNaN(options['doneSince']) ||
			    options['doneSince'] === 0) {
				console.error('%s: argument for "-t" must be ' +
				    'a non-negative integer', msArg0);
				usage();
			}
			break;

		case 'u':
			options['owner'] = option.optarg;
			break;

		case 'w':
			options['worker'] = option.optarg;
			break;

		case 'H':
			msParseable = true;
			break;

		case 'o':
			msParseable = true;
			msColumns = option.optarg.split(',');
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	clientInit(function (api) {
		var columns = mapColumns(msColumns || msColsJobs, msFieldsJobs);

		var table = new mod_tab.TableOutputStream({
		    'columns': columns,
		    'omitHeader': msParseable
		});

		var req = msApi.jobsList(options);

		req.on('error', function (err) {
			console.error('%s: failed to list jobs: %s',
			    msArg0, err.message);
			process.exit(1);
		});

		req.on('end', clientFini);

		req.on('record', function (record) {
			table.writeRow(makeJobRow(record['value'],
			    mod_jsprim.iso8601(new Date(record['_mtime']))));
		});
	});
}

/*
 * Given a list of column names and an object describing a node-tab
 * configuration, return a list of configuration objects corresopnding to each
 * column.
 */
function mapColumns(names, configs)
{
	var i, name, conf;
	var invalid = [], rv = [];

	for (i = 0; i < names.length; i++) {
		name = names[i].toLowerCase();
		if (msFieldAliases.hasOwnProperty(name))
			name = msFieldAliases[name];

		if (!configs.hasOwnProperty(name))
			invalid.push(names[i]);
		else {
			conf = Object.create(configs[name]);
			conf.alias = names[i].toUpperCase();
			rv.push(conf);
		}
	}

	if (invalid.length > 0) {
		console.error('invalid fields specified with -o: ' +
		    invalid.join(', '));
		usage();
	}

	return (rv);
}

/*
 * Given a raw job record and its mtime, return an object suitable for writing
 * to a table.
 */
function makeJobRow(job, mtime)
{
	var state = '';

	state = job['state'][0].toUpperCase();

	if (job['timeCancelled'])
		state = 'C' + state;
	else if (!job['input'] && !job['timeInputDone'])
		state = 'W' + state;

	return ({
	    'ASSIGNED': job['timeAssigned'] || '-',
	    'CANCELLED': job['timeCancelled'] || '-',
	    'CREATED': job['timeCreated'] || '-',
	    'DONE': job['timeDone'] || '-',
	    'INPUTDONE': job['timeInputDone'] || '-',
	    'JOBID': job['jobId'] || '-',
	    'JOBNAME': (job['jobName'] || '-').substr(0, 16),
	    'MODIFIED': mtime || '-',
	    'NIN': '-',
	    'NPH': (job['phases'] || []).length,
	    'OWNER': job['owner'] || '-',
	    'S': state,
	    'WORKER': job['worker'] || '-'
	});
}

function cmdGet()
{
	var argv, parser, option;

	argv = process.argv.slice(1);
	parser = new mod_getopt.BasicParser('v', argv);

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'v':
			msVerbose++;
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	if (parser.optind() >= argv.length)
		usage();

	msJobId = argv[parser.optind()];

	clientInit(function (api) {
		api.jobFetchDetails(msJobId, function (err, records) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);

				if (!records)
					process.exit(1);
			}

			printJobDetails(records);
			clientFini();
		});
	});
}

function printJobDetails(records)
{
	var job = records['job']['value'];
	var mtime = records['job']['_mtime'];
	var taskinputs = {};
	var taskoutputs = {};
	var taskslast = [];
	var nout = 0, ninter = 0, nerr = 0;
	var table, row, i, phase;

	records['taskinput'].forEach(function (record) {
		var taskid = record['value']['taskId'];

		if (!taskinputs[taskid])
			taskinputs[taskid] = [];

		taskinputs[taskid].push(record);
	});

	records['taskoutput'].forEach(function (record) {
		var taskid = record['value']['taskId'];

		if (!taskoutputs[taskid])
			taskoutputs[taskid] = [];

		if (record['value']['error'])
			nerr++;

		taskoutputs[taskid].push(record);
	});

	records['task'].forEach(function (record) {
		if (record['value']['state'] == 'cancelled' ||
		    record['value']['state'] == 'aborted' ||
		    record['value']['error'])
			nerr++;

		if (record['value']['phaseNum'] != job['phases'].length - 1 ||
		    !record['value']['timeCommitted']) {
			ninter += record['value']['nOutputs'] || 0;
			return;
		}

		if (record['value']['nOutputs'])
			nout += record['value']['nOutputs'];

		taskslast.push(record);
	});

	row = makeJobRow(job, mod_jsprim.iso8601(new Date(mtime)));

	mod_tab.emitTable({
	    'columns': mapColumns([ 'JobID', 'JobName' ], msFieldsJobs),
	    'rows': [ row ]
	});

	mod_tab.emitTable({
	    'columns': mapColumns([ 'User', 'Created' ], msFieldsJobs),
	    'rows': [ row ]
	});

	mod_tab.emitTable({
	    'columns': mapColumns([ 'Worker', 'Modified' ], msFieldsJobs),
	    'rows': [ row ]
	});

	mod_tab.emitTable({
	    'columns': [ {
		'label': 'STATE',
		'width': 15
	    }, {
		'label': 'NPHASES',
		'width': 7,
		'align': 'right'
	    }, {
		'label': 'NINPUT',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NTASKS',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NINTERMED',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NOUTPUT',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NERRORS',
		'width': 7,
		'align': 'right'
	    } ],
	    'rows': [ {
		/* XXX # of errors */
		'STATE': job['state'],
		'NPHASES': job['phases'].length,
		'NINPUT': records['jobinput'].length,
		'NTASKS': records['task'].length,
		'NINTERMED': ninter,
		'NOUTPUT': nout,
		'NERRORS': nerr
	    } ]
	});

	if (job['timeCancelled'])
		println('NOTE: Cancelled at %s', job['timeCancelled']);

	if (job['input'])
		println('NOTE: Job\'s input is piped from job "%s"',
		    job['input']);
	else if (!job['timeInputDone'])
		println('NOTE: Job is waiting for user input');

	println('');

	table = new mod_tab.TableOutputStream({
	    'columns': [ {
		'label': 'PHASE',
		'width': 5,
		'align': 'right'
	    }, {
		'label': 'TYPE',
		'width': 12
	    }, {
		'label': 'EXEC'
	    } ]
	});

	for (i = 0; i < job['phases'].length; i++) {
		phase = job['phases'][i];
		table.writeRow([ i, phase['type'] || 'storage-map',
		    '"' + phase['exec'] + '"' ]);
	}

	println('\nJOB INPUT OBJECTS', records['jobinput'].length);

	iterList(records['jobinput'], 3, function (record) {
		println('    %s', record['value']['key']);
	}, function () {
		println('    ...');
	});

	records['task'].sort(function (a, b) {
		var r1 = a['value']['phaseNum'] - b['value']['phaseNum'];
		if (r1 != 0)
			return (r1);
		if (a['value']['key'] < b['value']['key'])
			return (-1);
		if (a['value']['key'] > b['value']['keky'])
			return (1);
		return (0);
	});

	println('');
	table = new mod_tab.TableOutputStream({
	    'columns': [ {
		'label': 'TASKID',
		'width': 36
	    }, {
		'label': 'PH',
		'width': 3,
		'align': 'right'
	    }, {
		'label': 'S',
		'width': 4,
		'align': 'right'
	    }, {
		'label': 'RSLT',
		'width': 4,
		'align': 'right'
	    }, {
		'label': 'NOUT',
		'width': 4,
		'align': 'right'
	    } ]
	});

	iterList(records['task'], 3, function (record) {
		var taskid = record['value']['taskId'];
		var internal;

		table.writeRow([
		    record['value']['taskId'],
		    record['value']['phaseNum'],
		    msTaskStates[record['value']['state']] || '????',
		    record['value']['result'] || '-',
		    record['value']['nOutputs'] || 0
		]);

		var input = record['value']['key'] || (taskinputs[taskid] ?
		    taskinputs[taskid].length  + ' keys' : 'none');
		println('    INPUT:  %s', input);

		if (record['value']['error']) {
			var errobj = record['value']['error'];
			var message = errobj['message'] ||
			    '(no error specified)';

			internal = errobj['messageInternal'];

			println('    ERROR:  %s', message);

			if (internal)
				println('            internal error: %s',
				    internal);
		}

		if (taskinputs[taskid])
			iterList(taskinputs[taskid], 3, function (rec) {
				println('    INPUT:  %s', rec['value']['key']);
			}, function () { println('    ...'); });

		var outs = (record['value']['firstOutputs'] || []).map(
		    function (out) { return (out['key']); });
		outs = outs.concat((taskoutputs[taskid] || []).filter(
		    function (rec) { return (!rec['value']['error']); }).
		    map(
		    function (rec) { return (rec['value']['key']); }));

		iterList(outs, 1, function (out) {
			println('    OUTPUT: %s', out);
		}, function () { println('        ...'); });

		var errs = (record['value']['firstOutputs'] || []).filter(
		    function (out) { return (out['error']); }).map(
		    function (out) { return (out['error']); });
		errs = errs.concat((taskoutputs[taskid] || []).filter(
		    function (rec) { return (rec['value']['error']); }).map(
		    function (rec) { return (rec['value']['error']); }));

		iterList(errs, 1, function (error) {
			internal = error['messageInternal'];
			println('    ERROR:  %-10s  %s', error['code'],
			    error['message']);
			if (internal)
				println('            internal: %s', internal);
		}, function () { println('        ...'); });

		if (record['value']['stderr'])
			println('    STDERR: %s', record['value']['stderr']);
	}, function () { println('\n...\n'); });
}

function iterList(list, count, func, separator)
{
	if (msVerbose >= 1 || list.length <= 2 * count)
		list.forEach(func);
	else {
		list.slice(0, count).forEach(func);
		if (separator)
			separator();
		list.slice(list.length - count).forEach(func);
	}
}

function cmdLog()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchLog(jobid);
		var entries = [];

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to fetch log: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('log', function (entry) {
			entries.push(entry);
		});

		rv.on('end', function () {
			logPrint(entries);
			clientFini();
		});
	});
}

function logPrint(entries)
{
	var timestamp, where;

	sortStable(entries, function (a, b) {
		return (a['time'] - b['time']);
	});

	for (var i = 0; i < entries.length; i++) {
		timestamp = mod_jsprim.iso8601(entries[i]['time']);

		/* Chop off the year and "Z" */
		entries[i]['walltime'] = timestamp.substr(5,
		    timestamp.length - 6);
		entries[i]['jobtime'] = formatDuration(
		    entries[i]['time'] - entries[0]['time']);

		where = entries[i]['where'];
		if (where.length > 11)
			where = where.substr(0, 8) + '...';
		entries[i]['where'] = where;
	}

	mod_tab.emitTable({
	    'rows': entries,
	    'columns': [ {
		'label': 'walltime',
		'alias': 'TIMESTAMP',
		'width': 18
	    }, {
		'label': 'jobtime',
		'alias': 'JOBTIME',
		'width': 8,
		'align': 'right'
	    }, {
		'label': 'where',
		'alias': 'WHERE',
		'width': 11
	    }, {
		'label': 'message',
		'alias': 'MESSAGE',
		'width': 12
	    }, {
		'label': 'what',
		'alias': 'WHAT',
		'width': 11
	    } ]
	});
}

function formatDuration(millis)
{
	if (millis < 60000)
		return (sprintf('%d.%03d', Math.floor(millis / 1000),
		    millis % 1000));

	var minutes = Math.floor(millis / 60000);
	millis %= 60000;

	return (sprintf('%d:%02d.%03ds', minutes,
	    Math.floor(millis / 1000), millis % 1000));
}

function sortStable(list, comparator)
{
	if (!comparator)
		comparator = function (a, b) {
			return ((a < b) ? -1 : (a > b) ? 1 : 0);
		};

	/*
	 * Since JavaScript's sort is not stable, we have no choice but to use
	 * O(N) space to keep track of each element's index.  We create an
	 * array of just the indices, then sort that by the corresponding value
	 * in "list".
	 */
	var tosort = list.map(function (_, i) { return (i); });

	tosort.sort(function (a, b) {
		var rv = comparator(list[a], list[b]);
		if (rv !== 0)
			return (rv);
		return (a - b);
	});

	/*
	 * Although we had to use O(N) space anyway, it's nice to keep the same
	 * contract as Array.sort by updating the array in place.
	 */
	tosort = tosort.map(function (i) { return (list[i]); });
	for (var j = 0; j < list.length; j++)
		list[j] = tosort[j];

	return (list);
}

main();
