#!/usr/bin/env node

/*
 * mrjob: submit jobs directly to Marlin via Moray (i.e. not through Muskie)
 * This is a dev tool.
 */

var mod_assert = require('assert');
var mod_path = require('path');
var mod_url = require('url');

var mod_bunyan = require('bunyan');
var mod_extsprintf = require('extsprintf');
var mod_getopt = require('posix-getopt');
var mod_jsprim = require('jsprim');
var mod_tab = require('tab');
var mod_uuid = require('node-uuid');
var mod_verror = require('verror');
var mod_vasync = require('vasync');
var mod_wordwrap = require('wordwrap');

var wrap = mod_wordwrap(80);
var wrap4 = mod_wordwrap(4, 80);
var println = function () {
	console.log(mod_extsprintf.sprintf.apply(null,
	    Array.prototype.slice.call(arguments)));
};

var mod_marlin = require('../lib/marlin');

var msArg0 = mod_path.basename(process.argv[1]);
var msUsage = [
    'USAGE: mrjob submit   [-i id] [-n name] [-m exec] [-r exec] ...',
    '       mrjob addkeys  jobid [key ...]',
    '       mrjob listkeys jobid',
    '       mrjob endinput jobid',
    '       mrjob cancel   jobid',
    '       mrjob outputs  jobid',
    '       mrjob failed   jobid',
    '       mrjob errors   jobid',
    '       mrjob list     [-H] [-o field1[,field2...]]',
    '       mrjob get      [-v] jobid',
    '',
    '    Manages Marlin jobs via Moray.',
    '',
    'SUBCOMMANDS',
    '',
    '   submit [-i id] [-n name] [-m exec] [-r exec]',
    '',
    '      Submit a new job without ending input.',
    '',
    '          -i id          Use "id" for the job\'s id',
    '          -m exec        Append a map phase with body "exec"',
    '          -n name        Use "name" for the job\'s name',
    '          -r exec        Append a reduce phase with body "exec"',
    '',
    '      With no -m or -r options, the job gets one map phase.',
    '',
    '   addkeys jobid [key ...]',
    '',
    '       Submit new keys for a job (which may or may not already exist).',
    '',
    '   listkeys jobid',
    '',
    '       Lists all keys submitted for a job.',
    '',
    '   endinput jobid',
    '',
    '       Indicate that no further keys will be added for a job.',
    '',
    '   cancel jobid',
    '',
    '       Mark a job job cancelled.',
    '',
    '   outputs jobid',
    '',
    '       List objects emitted by a job.',
    '',
    '   failed jobid',
    '',
    '       Lists job input keys whose processing failed, either during the ',
    '       first phase or a subsequent phase.  Note that failures during or ',
    '       after any reduce phase cannot be tracked back to the original ',
    '       input key, so such failures will not be represented in this ',
    '       output.',
    '',
    '   errors jobid',
    '',
    '       Lists errors that occurred while processing the given job.',
    '',
    '   list [-H] [-o field1[,field2...]]',
    '',
    '       Lists all jobs.  The default output mode is a human-readable, ',
    '       unstable output format.  With -H, the output is a simple table ',
    '       with no header row.  Individual columns may be selected using -o',
    '       as with ps(1) and other tools.  -o implies -H.',
    '',
    '   get [-v] jobid',
    '',
    '       Fetch details about the given job.',
    '',
    'MORAY',
    '',
    '   The remote Moray instance to use must be specified via the MORAY_URL ',
    '   environment variable, which should have the form "tcp://host:port/"',
    '',
    'EXAMPLE: Create a "word count" job',
    '',
    '    # mrjob submit -m wc -r "awk {sum += $1} END { print sum; }"',
    '    34cae1fd-8f9e-48cb-9163-7e2b365fc394',
    '',
    '    # mrjob addkeys 34cae1fd-8f9e-48cb-9163-7e2b365fc394 key1 ...',
    '    # mrjob endinput 34cae1fd-8f9e-48cb-9163-7e2b365fc394',
    '',
    'COLUMNS',
    '',
    '    The following columns are available when listing jobs:'
].join('\n');

var msPhases = [];
var msJobName = 'mrsubmit job';
var msJobId = mod_uuid.v4();
var msMorayUrl = process.env['MORAY_URL'];
var msParseable = false;		/* whether output should be parseable */
var msVerbose = 0;			/* whether output should be verbose */
var msColumns;				/* user-specified list of columns */

var msApi;	/* marlin api */
var msLog;	/* bunyan logger */
var msCommands = {
    'submit': cmdSubmit,
    'addkeys': cmdAddkeys,
    'listkeys': cmdListkeys,
    'endinput': cmdEndinput,
    'cancel': cmdCancel,
    'list': cmdList,
    'outputs': cmdOutputs,
    'errors': cmdErrors,
    'failed': cmdFailed,
    'get': cmdGet
};

/* default set of columns for list-of-jobs */
var msColsJobs = [ 'JobId', 'S', 'NPh', 'Modified' ];

/* node-tab configuration for list-of-jobs table */
var msFieldsJobs = {
    'assigned': {
	'label': 'ASSIGNED',
	'width': 24
    },
    'cancelled': {
	'label': 'CANCELLED',
	'width': 24
    },
    'created': {
	'label': 'CREATED',
	'width': 24
    },
    'done': {
	'label': 'DONE',
	'width': 24
    },
    'inputdone': {
	'label': 'INPUTDONE',
	'width': 24
    },
    'jobid': {
	'label': 'JOBID',
	'width': 36
    },
    'jobname': {
	'label': 'JOBNAME',
	'width': 24
    },
    'modified': {
	'label': 'MODIFIED',
	'width': 24,
	'doc': 'last modified time'
    },
    'nin': {
	/* XXX remove? */
	'label': 'NIN',
	'width': 5,
	'align': 'right'
    },
    'nph': {
	'label': 'NPH',
	'width': 3,
	'align': 'right',
	'doc': 'number of phases'
    },
    'owner': {
	'label': 'OWNER',
	'width': 36
    },
    's': {
	'label': 'S',
	'width': 5,
	'align': 'right',
	'doc': 'state'
    },
    'worker': {
	'label': 'WORKER',
	'width': 36
    }
};

/*
 * Aliases: the keys in this object may be used as field names with -o, but
 * each one is just an alias for the corresponding value.
 */
var msFieldAliases = {
    'crtime': 'created',
    'cust': 'owner',
    'customer': 'owner',
    'mtime': 'modified',
    'state': 's',
    'user': 'owner'
};

/* Mapping of task state values to a shorter form for display. */
var msTaskStates = {
    'aborted': 'abrt',
    'dispatched': 'disp',
    'running': 'run',
    'cancelled': 'cncl',
    'done': 'done'
};

function usage()
{
	function docFields(conf, list) {
		return (Object.keys(conf).map(function (f) {
			var rv = conf[f]['label'];
			if (conf[f]['doc'])
				rv += ' (' + conf[f]['doc'] + ')';
			return (rv);
		}).join(', '));
	}

	console.error(msUsage);
	console.error(wrap4(docFields(msFieldsJobs) + '\n'));
	process.exit(2);
}

function main()
{
	var subcmd;

	if (process.argv.length < 3)
		usage();

	subcmd = process.argv[2];

	if (!msCommands.hasOwnProperty(subcmd))
		usage();

	if (!msMorayUrl) {
		console.error('MORAY_URL must be specified in the environment');
		process.exit(2);
	}

	msLog = new mod_bunyan({
	    'name': msArg0,
	    'level': process.env['LOG_LEVEL'] || 'warn',
	    'stream': process.stderr
	});

	msCommands[subcmd]();
}

function clientInit(callback)
{
	mod_marlin.createClient({
	    'moray': { 'url': msMorayUrl },
	    'log': msLog
	}, function (err, api) {
		if (err) {
			console.error('%s: %s', msArg0, err.message);
			process.exit(1);
		}

		msApi = api;
		callback(msApi);
	});
}

function clientFini()
{
	msApi.close();
}

function cmdSubmit()
{
	var parser, option;

	parser = new mod_getopt.BasicParser('c:i:m:n:r:',
	    process.argv.slice(1));

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'i':
			msJobId = option.optarg;
			break;

		case 'n':
			msJobName = option.optarg;
			break;

		case 'm':
		case 'r':
			msPhases.push({
			    'type': option.option == 'm' ?
				'storage-map' : 'reduce',
			    'exec': option.optarg
			});
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	if (msPhases.length === 0)
		msPhases.push({ 'type': 'storage-map', 'exec': 'echo' });

	var job = {
	    'jobId': msJobId,
	    'jobName': msJobName,
	    'phases': msPhases,
	    'owner': process.env['USER']
	};

	clientInit(function (api) {
		api.jobCreate(job, function (err, jobid) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			console.log(jobid);
			clientFini();
		});
	});
}

function cmdAddkeys()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];
	var keys = process.argv.slice(4);

	if (keys.length === 0)
		return;

	clientInit(function (api) {
		mod_vasync.forEachParallel({
		    'inputs': keys,
		    'func': function (key, callback) {
			api.jobAddKey(jobid, key, function (err) {
				if (!err)
					console.log(key);
				else
					console.error('%s: key "%s": %s',
					    msArg0, key, err.message);
				callback();
			});
		    }
		}, clientFini);
	});
}

function cmdListkeys()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchInputs(jobid);

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to list inputs: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('key', function (key) {
			console.log(key);
		});

		rv.on('end', clientFini);
	});
}

function cmdEndinput()
{
	if (process.argv.length < 4)
		usage();

	var opts = {
	    'retry': {
		'retries': 1,
		'maxTimeout': 1000
	    }
	};

	clientInit(function (api) {
		api.jobEndInput(process.argv[3], opts, function (err, record) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			var job = record['value'];
			if (job['timeInputDone'])
				console.error(
				    'warning: job\'s input already ended');

			if (job['timeCancelled'])
				console.error('warning: job already cancelled');

			if (job['state'] == 'done')
				console.error('warning: job already done');

			clientFini();
		});
	});
}

function cmdCancel()
{
	if (process.argv.length < 4)
		usage();

	var opts = {
	    'retry': {
		'retries': 1,
		'maxTimeout': 1000
	    }
	};

	clientInit(function (api) {
		api.jobCancel(process.argv[3], opts, function (err, record) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);
				process.exit(1);
			}

			var job = record['value'];
			if (job['timeCancelled'])
				console.error('warning: job already cancelled');

			if (job['state'] == 'done')
				console.error('warning: job already done');

			clientFini();
		});
	});
}

function cmdOutputs()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		api.jobFetch(jobid, function (err, record) {
			if (err) {
				console.error('%s: job "%s": ' +
				    'failed to fetch: %s', msArg0, jobid,
				    err.message);
				process.exit(1);
			}

			var rv = api.jobFetchOutputs(jobid,
			    record['value']['phases'].length - 1);

			rv.on('error', function (suberr) {
				console.error('%s: job "%s": failed to list ' +
				    'outputs: %s', msArg0, jobid,
				    suberr.message);
				process.exit(1);
			});

			rv.on('key', function (key) {
				console.log('%s', key);
			});

			rv.on('end', clientFini);
		});
	});
}

function cmdErrors()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchErrors(jobid);

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to list errors: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('err', function (error) {
			console.log('%s: %s', error['what'], error['message']);
		});

		rv.on('end', clientFini);
	});
}

function cmdFailed()
{
	if (process.argv.length < 4)
		usage();

	var jobid = process.argv[3];

	clientInit(function (api) {
		var rv = api.jobFetchFailedJobInputs(jobid);

		rv.on('error', function (err) {
			console.error('%s: job "%s": failed to list failed: %s',
			    msArg0, jobid, err.message);
			process.exit(1);
		});

		rv.on('key', function (key) {
			console.log(key);
		});

		rv.on('end', clientFini);
	});
}

function cmdList()
{
	var argv, parser, option;

	argv = process.argv.slice(1);
	parser = new mod_getopt.BasicParser('Ho:', argv);

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'H':
			msParseable = true;
			break;

		case 'o':
			msParseable = true;
			msColumns = option.optarg.split(',');
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	clientInit(function (api) {
		var columns = mapColumns(msColumns || msColsJobs, msFieldsJobs);

		var table = new mod_tab.TableOutputStream({
		    'columns': columns,
		    'omitHeader': msParseable
		});

		var req = msApi.jobsList();

		req.on('error', function (err) {
			console.error('%s: failed to list jobs: %s',
			    msArg0, err.message);
			process.exit(1);
		});

		req.on('end', clientFini);

		req.on('record', function (record) {
			table.writeRow(makeJobRow(record['value'],
			    mod_jsprim.iso8601(new Date(record['_mtime']))));
		});
	});
}

/*
 * Given a list of column names and an object describing a node-tab
 * configuration, return a list of configuration objects corresopnding to each
 * column.
 */
function mapColumns(names, configs)
{
	var i, name, conf;
	var invalid = [], rv = [];

	for (i = 0; i < names.length; i++) {
		name = names[i].toLowerCase();
		if (msFieldAliases.hasOwnProperty(name))
			name = msFieldAliases[name];

		if (!configs.hasOwnProperty(name))
			invalid.push(names[i]);
		else {
			conf = Object.create(configs[name]);
			conf.alias = names[i].toUpperCase();
			rv.push(conf);
		}
	}

	if (invalid.length > 0) {
		console.error('invalid fields specified with -o: ' +
		    invalid.join(', '));
		usage();
	}

	return (rv);
}

/*
 * Given a raw job record and its mtime, return an object suitable for writing
 * to a table.
 */
function makeJobRow(job, mtime)
{
	var state = '';

	state = job['state'][0].toUpperCase();

	if (job['timeCancelled'])
		state = 'C' + state;
	else if (!job['timeInputDone'])
		state = 'W' + state;

	return ({
	    'ASSIGNED': job['timeAssigned'] || '-',
	    'CANCELLED': job['timeCancelled'] || '-',
	    'CREATED': job['timeCreated'] || '-',
	    'DONE': job['timeDONE'] || '-',
	    'INPUTDONE': job['timeInputDone'] || '-',
	    'JOBID': job['jobId'] || '-',
	    'JOBNAME': (job['jobName'] || '-').substr(0, 16),
	    'MODIFIED': mtime || '-',
	    'NIN': '-',
	    'NPH': (job['phases'] || []).length,
	    'OWNER': job['owner'] || '-',
	    'S': state,
	    'WORKER': job['worker'] || '-'
	});
}

function cmdGet()
{
	var argv, parser, option;

	argv = process.argv.slice(1);
	parser = new mod_getopt.BasicParser('v', argv);

	while ((option = parser.getopt()) !== undefined) {
		switch (option.option) {
		case 'v':
			msVerbose++;
			break;

		default:
			/* error message already emitted by getopt */
			mod_assert.equal('?', option.option);
			usage();
			break;
		}
	}

	if (parser.optind() >= argv.length)
		usage();

	msJobId = argv[parser.optind()];

	clientInit(function (api) {
		api.jobFetchDetails(msJobId, function (err, records) {
			if (err) {
				console.error('%s: %s', msArg0, err.message);

				if (!records)
					process.exit(1);
			}

			printJobDetails(records);
			clientFini();
		});
	});
}

function printJobDetails(records)
{
	var job = records['job']['value'];
	var mtime = records['job']['_mtime'];
	var taskinputs = {};
	var taskoutputs = {};
	var taskslast = [];
	var nout = 0, ninter = 0, nerr = 0;
	var table, row, i, phase;

	records['taskinput'].forEach(function (record) {
		var taskid = record['value']['taskId'];

		if (!taskinputs[taskid])
			taskinputs[taskid] = [];

		taskinputs[taskid].push(record);
	});

	records['taskoutput'].forEach(function (record) {
		var taskid = record['value']['taskId'];

		if (!taskoutputs[taskid])
			taskoutputs[taskid] = [];

		if (record['value']['error'])
			nerr++;

		taskoutputs[taskid].push(record);
	});

	records['task'].forEach(function (record) {
		if (record['value']['state'] == 'cancelled' ||
		    record['value']['state'] == 'aborted' ||
		    record['value']['error'])
			nerr++;

		if (record['value']['phaseNum'] != job['phases'].length - 1 ||
		    !record['value']['timeCommitted']) {
			ninter += record['value']['nOutputs'] || 0;
			return;
		}

		if (record['value']['nOutputs'])
			nout += record['value']['nOutputs'];

		taskslast.push(record);
	});

	row = makeJobRow(job, mod_jsprim.iso8601(new Date(mtime)));

	mod_tab.emitTable({
	    'columns': mapColumns([ 'JobID', 'JobName' ], msFieldsJobs),
	    'rows': [ row ]
	});

	mod_tab.emitTable({
	    'columns': mapColumns([ 'User', 'Created' ], msFieldsJobs),
	    'rows': [ row ]
	});

	mod_tab.emitTable({
	    'columns': mapColumns([ 'Worker', 'Modified' ], msFieldsJobs),
	    'rows': [ row ]
	});

	mod_tab.emitTable({
	    'columns': [ {
		'label': 'STATE',
		'width': 15
	    }, {
		'label': 'NPHASES',
		'width': 7,
		'align': 'right'
	    }, {
		'label': 'NINPUT',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NTASKS',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NINTERMED',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NOUTPUT',
		'width': 10,
		'align': 'right'
	    }, {
		'label': 'NERRORS',
		'width': 7,
		'align': 'right'
	    } ],
	    'rows': [ {
		/* XXX # of errors */
		'STATE': job['state'],
		'NPHASES': job['phases'].length,
		'NINPUT': records['jobinput'].length,
		'NTASKS': records['task'].length,
		'NINTERMED': ninter,
		'NOUTPUT': nout,
		'NERRORS': nerr
	    } ]
	});

	if (job['timeCancelled'])
		println('NOTE: Cancelled at %s', job['timeCancelled']);
	if (!job['timeInputDone'])
		println('NOTE: Job is waiting for user input');
	println('');

	table = new mod_tab.TableOutputStream({
	    'columns': [ {
		'label': 'PHASE',
		'width': 5,
		'align': 'right'
	    }, {
		'label': 'TYPE',
		'width': 12
	    }, {
		'label': 'EXEC'
	    } ]
	});

	for (i = 0; i < job['phases'].length; i++) {
		phase = job['phases'][i];
		table.writeRow([ i, phase['type'] || 'storage-map',
		    '"' + phase['exec'] + '"' ]);
	}

	println('\nJOB INPUT OBJECTS', records['jobinput'].length);

	iterList(records['jobinput'], 3, function (record) {
		println('    %s', record['value']['key']);
	}, function () {
		println('    ...');
	});

	records['task'].sort(function (a, b) {
		var r1 = a['value']['phaseNum'] - b['value']['phaseNum'];
		if (r1 != 0)
			return (r1);
		if (a['value']['key'] < b['value']['key'])
			return (-1);
		if (a['value']['key'] > b['value']['keky'])
			return (1);
		return (0);
	});

	println('');
	table = new mod_tab.TableOutputStream({
	    'columns': [ {
		'label': 'TASKID',
		'width': 36
	    }, {
		'label': 'PH',
		'width': 3,
		'align': 'right'
	    }, {
		'label': 'S',
		'width': 4,
		'align': 'right'
	    }, {
		'label': 'RSLT',
		'width': 4,
		'align': 'right'
	    }, {
		'label': 'NOUT',
		'width': 4,
		'align': 'right'
	    } ]
	});

	iterList(records['task'], 3, function (record) {
		var taskid = record['value']['taskId'];

		table.writeRow([
		    record['value']['taskId'],
		    record['value']['phaseNum'],
		    msTaskStates[record['value']['state']] || '????',
		    record['value']['result'] || '-',
		    record['value']['nOutputs'] || 0
		]);

		var input = record['value']['key'] || (taskinputs[taskid] ?
		    taskinputs[taskid].length  + ' keys' : 'none');
		println('    INPUT:  %s', input);

		if (record['value']['error']) {
			var message = record['value']['error']['message'] ||
			    '(no error specified)';
			println('    ERROR:  %s', message);
		}

		if (taskinputs[taskid])
			iterList(taskinputs[taskid], 3, function (rec) {
				println('    INPUT:  %s', rec['value']['key']);
			}, function () { println('    ...'); });

		var outs = (record['value']['firstOutputs'] || []).map(
		    function (out) { return (out['key']); });
		outs = outs.concat((taskoutputs[taskid] || []).filter(
		    function (rec) { return (!rec['value']['error']); }).
		    map(
		    function (rec) { return (rec['value']['key']); }));

		iterList(outs, 1, function (out) {
			println('    OUTPUT: %s', out);
		}, function () { println('        ...'); });
	}, function () { println('\n...\n'); });
}

function iterList(list, count, func, separator)
{
	if (msVerbose >= 1 || list.length <= 2 * count)
		list.forEach(func);
	else {
		list.slice(0, count).forEach(func);
		if (separator)
			separator();
		list.slice(list.length - count).forEach(func);
	}
}

main();
