#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2016, Joyent, Inc.
#

#
# mrdeploycompute: combines the steps of provisioning a new compute zone for
# Marlin, adding it to the agent, and saving the name in a file for pick up when
# the agent restarts.
#

set -o pipefail
set -o xtrace

# This program is run under Ur without any useful PATH.
export PATH=$PATH:/usr/sbin:/opt/smartdc/bin

mdc_arg0="$(basename $0)"
mdc_zonename="$1"
mdc_tmpfile="/var/tmp/$mdc_arg0.$$"
mdc_tools="$(dirname $0)"

function fail
{
	echo "$mdc_arg0: $*" >&2
	exit 1
}

function usage
{
	echo "usage: $mdc_arg0 zonename" >&2
	exit 2
}

[[ -n "$mdc_zonename" ]] || usage

vmadm list | awk '{print $1}' | grep -w "$mdc_zonename" || \
    fail "no such zone: $mdc_zonename"

echo "Creating snapshot zones/$mdc_zonename@marlin_init ... \c "
zfs snapshot zones/$mdc_zonename@marlin_init
echo "done."

#
# mrzone failure is not fatal, since compute zones can be deployed before the
# agent is running.
#
$mdc_tools/mrzone $mdc_zonename
rm -f $mdc_tmpfile
