#!/bin/bash

set -o pipefail

function fail
{
	echo "$*" >&2
	exit 1
}

[[ -n "$1" ]] || fail "usage: $(basename $0) zonename"

echo '{ "set_tags": { "manta_compute": "" } }' | vmadm update $1 || \
    fail "failed to mark zone non-removed"
exec curl -X POST -is \
    "${AGENT_URL:-http://localhost:9080}/zones?zonename=$1" | json
