#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

set -o pipefail

function fail
{
	echo "$*" >&2
	exit 1
}

[[ -n "$1" ]] || fail "usage: $(basename $0) zonename"

echo '{ "set_tags": { "manta_compute": "" } }' | vmadm update $1 || \
    fail "failed to mark zone non-removed"
exec curl -X POST -is \
    "${AGENT_URL:-http://localhost:9080}/zones?zonename=$1" | json
