#!/bin/bash

set -o pipefail

function fail
{
	echo "$*" >&2
	exit 1
}

[[ -n "$1" ]] || fail "usage: $(basename $0) zonename"

exec curl -X POST -is \
    "${AGENT_URL:-http://localhost:9080}/zones?zonename=$1" | json
