#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

#
# mrzonedisable: remove a zone from Marlin service temporarily
#

arg0=$(basename $0)

if [[ -h "$0" ]]; then
	cd $(dirname $0)
	. $(dirname $(readlink "$arg0"))/../tools/util.sh
else
	. $(dirname $0)/../tools/util.sh
fi

if [[ $# -ne 1 ]]; then
	echo "usage: $arg0 ZONENAME" >&2
	echo "Temporarily remove a zone from Marlin service." >&2
	exit 2
fi

zone_disable "$1"
