#!/bin/bash

#
# mkjobs: submit N instances of a given job
#

function fail
{
	echo "$*" >&2
	exit 1
}

function usage
{
	echo "$mj_arg0 COUNT < JOB_TEMPLATE" >&2
	echo "Submit N copies of the given job template in JSON form."
	exit 2
}

mj_arg0=$(basename $0)
mj_count=$1
mj_tmpfile=/var/tmp/$mj_arg0.$$
[[ -n "$mj_count" ]] || usage
[[ $mj_count =~ ^[0-9]+$ ]] || fail "not a number: $mj_count"

json > $mj_tmpfile || fail "invalid JSON input"

for (( i = 1; i <= $mj_count; i++ )) {
	json -e "jobName = '$mj_arg0 $i/$mj_count: ' + jobName" < $mj_tmpfile |
	    $(dirname $0)/mrpost | grep Location ||
	    echo "failed to create job $i" >&2
}

rm -f $mj_tmpfile
