#!/bin/bash

#
# mrpost: submit a new job to Marlin
# usage: mrpost [-f] < filename
#

mrp_tmpfile=/var/tmp/mrpost.$$

opt_f=false
if [[ "$1" = "-f" ]]; then
	opt_f=true
fi

[[ -z "$MARLIN_URL" ]] && MARLIN_URL=http://localhost:8080
curl -is -X POST -H "Content-type: application/json" \
    -H"Accept: application/json" -T- $MARLIN_URL/jobs | json > $mrp_tmpfile
cat $mrp_tmpfile
head -3 $mrp_tmpfile | tail -1 | grep "HTTP/1.1 201 Created" > /dev/null || \
    exit 1

if [[ $opt_f = "false" ]]; then
	rm -f $mrp_tmpfile
	exit 0
fi

mrp_uri=$(grep '^Location:' $mrp_tmpfile | head -1 | \
    awk '{print $2}' | tr -d '\r')
if [[ -n $mpr_uri ]]; then
	echo "couldn't find new job URI" >&2
	exit 1
fi

rm -f $mrp_tmpfile

while :; do
	curl -s $MARLIN_URL$mrp_uri | json
	sleep 1
done
