#!/bin/bash

set -o pipefail

function fail
{
	echo "$*" >&2
	exit 1
}

[[ -n "$1" ]] || fail "usage: $(basename $0) taskfile.json"

exec curl -X POST -is -H'content-type: application/json' \
    -T $1 "http://localhost:8080/tasks" | json
