#!/bin/bash

#
# mrwipe url: remove Marlin buckets from a given Moray instance
#

shopt -s xpg_echo

if ! [[ -n "$1" ]]; then
	echo "usage: $(basename $0) moray-host" >&2
	echo >&2
	echo "Removes Marlin data from a given Moray instance." >&2
	echo "This operation is NOT reversible!" >&2
	exit 2
fi

function fail
{
	echo "$*" >&2
	exit 1
}

mw_buckets="marlin_jobs marlin_jobinputs marlin_tasks marlin_taskinputs "
mw_buckets="$mw_buckets marlin_taskoutputs"

for bucket in $mw_buckets; do
	echo -n "Removing $bucket bucket ... \c"
	$(dirname $0)/../node_modules/moray/bin/delbucket -h "$1" "$bucket" || \
	    fail "FAILED."
	echo "done."
done
